on:
  push:
    branches:
      - '*'

jobs:
  build_test:
    runs-on: ubuntu-latest
    name: Test building HTML of IFE model
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Export and validate model
      uses: materpillar/capella-html-exporter@v6
      with:
        entrypoint: ./entrypoint.sh
        model-name: capella-automations
        path-model-folder: capella-automations

    - name: Archive HTML export and validation report
      uses: actions/upload-artifact@v3
      with:
        name: validation-report-html-export
        path: artifacts